# Generated by Django 5.0.7 on 2024-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('preparation_time', models.CharField(max_length=10)),
            ],
        ),
    ]
